# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171014_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctimages',
            old_name='PhotometriInterpretation',
            new_name='PhotometricInterpretation',
        ),
    ]
