# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171014_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctimages',
            name='ImageType',
            field=models.CharField(max_length=100),
        ),
    ]
