# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171014_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctimages',
            name='BodypartExamined',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ctimages',
            name='ImageOrientationPatient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ctimages',
            name='ImagePositionPatient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ctimages',
            name='SliceThickness',
            field=models.CharField(max_length=100),
        ),
    ]
